#!/bin/bash 

echo "PYTHONPATH: $PYTHONPATH"
#echo "HOMEobsmon: $HOMEobsmon"
#echo "COMOUT: $COMOUT"
#echo "MODEL: $MODEL"
#echo "PDY: $PDY"
#echo "cyc: $cyc"
#echo "DATAROOT: $DATAROOT"
#echo "APRUN_PY: $APRUN_PY"
echo "PATH: $PATH"
echo "initial module list"
module list
echo ""
echo ""

module purge
echo "after module purge"
module list

module load PrgEnv-intel/8.3.3
module load craype/2.7.17
module load cray-pals/1.2.2
module load git/2.29.0
module load intel/19.1.3.304
module load python/3.10.4
module load ve/evs/1.0
module load libfabric/1.11.0.0
echo ""
echo "reloaded modules"
`module list`

export PATH=$PATH:/lfs/h2/emc/da/noscrub/edward.safford/eva/opt/bin
export PYTHONPATH=$PYTHONPATH:/lfs/h2/emc/da/noscrub/edward.safford/eva/opt/

###########################
# J-job for Mon Plot Obs
###########################
export NET="obsmon"
export PDATE="${PDY}${cyc}"

############################
# Define package locations
############################
export HOMEobsmon=${HOMEobsmon:-${PACKAGEROOT}/${NET}.${obsmon_ver}}
export SCRIPTSobsmon=${SCRIPTSobsmon:-${HOMEobsmon}/scripts}
export PARMobsmon=${PARMobsmon:-${HOMEobsmon}/parm}
export CNTRLobsmon=${CNTRLobsmon:-${PARMobsmon}/cntrl}
export USHobsmon=${USHobsmon:-${HOMEobsmon}/ush}

################################
# Define plot output location
################################
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${obsmon_ver})}
export COMOUTplots=${COMOUTplots:-${COMOUT}/${MODEL}/${PDATE}}
mkdir -m 775 -p $COMOUTplots

###################################
# Create $DATA for temp workspace
###################################
export DATA=${DATA:-${DATAROOT}/${NET}/${MODEL}/Plot}
if [[ -d ${DATA} ]]; then rm -rf ${DATA}; fi

mkdir -p ${DATA}
cd ${DATA}

################
# Run exscript
################
${OBSMON_PLOT:-${SCRIPTSobsmon}/exobsmon_plot.sh}
status=$?
[[ ${status} -ne 0 ]] && exit ${status}

####################
# Final processing
####################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

####################
# Remove workspace
####################
#KEEPDATA=${KEEPDATA:-"NO"}
#cd ${DATAROOT}
#[[ ${KEEPDATA} = "NO" ]] && rm -rf ${DATA}

report-mem
