ob_types:

  viirs_npp:
    datasets:
      - filenames_template:
          template: "{{ runtime_dir }}/viirs_npp_%Y%m%d%H_output_aod.nc"
        groups:
          - name: "oman/aerosolOpticalDepth"
            variables: [mean, count, RMS]
        variables: [validTime]

    figures:
      - use: time_series_multi_line
        params:
          title: "{{ ob_type }} Time Series - Assimilated Mean O-A\n[[start_YMDH]]-[[end_YMDH]]"
          variable: "aerosolOpticalDepth"
          y_label: "aerosolOpticalDepth (Mean)"
          output: "[[runtime_dir]]/plots/{{ ob_type }}/aerosolOpticalDepth/{{ ob_type }}_time_series_[[start_YMDH]]_[[end_YMDH]].png"
          series:
            - series_label: "aerosolOpticalDepth"
              series_color: "black"
              series_y: "ObsMonitor::oman_aerosolOpticalDepth::mean"
              series_slices: "[:,0]"

  viirs_n20:
    datasets:
      - filenames_template:
          template: "{{ runtime_dir }}/viirs_n20_%Y%m%d%H_output_aod.nc"
        groups:
          - name: "oman/aerosolOpticalDepth"
            variables: [mean, count, RMS]
        variables: [validTime]

    figures:
      - use: time_series_multi_line
        params:
          title: "{{ ob_type }} Time Series - Mean O-A\n[[start_YMDH]]-[[end_YMDH]]"
          variable: "aerosolOpticalDepth"
          y_label: "aerosolOpticalDepth (Mean)"
          output: "[[runtime_dir]]/plots/{{ ob_type }}/aerosolOpticalDepth/{{ ob_type }}_time_series_[[start_YMDH]]_[[end_YMDH]].png"
          series:
            - series_label: "aerosolOpticalDepth"
              series_color: "black"
              series_y: "ObsMonitor::oman_aerosolOpticalDepth::mean"
              series_slices: "[:,0]"

  viirs_n21:
    datasets:
      - filenames_template:
          template: "{{ runtime_dir }}/viirs_n21_%Y%m%d%H_output_aod.nc"
        groups:
          - name: "oman/aerosolOpticalDepth"
            variables: [mean, count, RMS]
        variables: [validTime]
