ob_types:
  radiance_gmi_gpm:
    channels: []
    datasets:
      - filenames_template:
          template: "{{ runtime_dir }}/radiance_gmi_gpm_%Y%m%d%H_output_atmos.nc"
        groups:
          - name: "byDomains/ombg/brightnessTemperature"
            variables: &radiance_stats
              - assimilated_count
              - assimilated_mean
              - assimilated_RMS
              - monitored_count
              - monitored_mean
              - monitored_RMS
              - rejected_count
              - rejected_mean
              - rejected_RMS
          - name: "byDomains/oman/brightnessTemperature"
            variables: *radiance_stats
          - name: "griddedBins/ombg/brightnessTemperature"
            variables: [latitude, longitude]
          - name: "griddedBins/oman/brightnessTemperature"
            variables: [latitude, longitude]
        variables: [validTime]
