ob_types:
  radiance_atms_n20:
    channels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]
    datasets:
      - filenames_template:
          template: "{{ runtime_dir }}/radiance_atms_n20_%Y%m%d%H_output_atmos.nc"
        groups:
          - name: "byDomains/ombg/brightnessTemperature"
            variables: &radiance_stats
              - assimilated_count
              - assimilated_mean
              - assimilated_RMS
              - monitored_count
              - monitored_mean
              - monitored_RMS
              - rejected_count
              - rejected_mean
              - rejected_RMS
          - name: "byDomains/oman/brightnessTemperature"
            variables: *radiance_stats
          - name: "griddedBins/ombg/brightnessTemperature"
            variables: [latitude, longitude]
          - name: "griddedBins/oman/brightnessTemperature"
            variables: [latitude, longitude]
        variables: [validTime]
