ob_types:

  snocvr:
    datasets:
      - filenames_template:
          template: "{{ runtime_dir }}/snocvr_%Y%m%d%H_output_snow.nc"
        groups:
          - name: "byDomains/ombg/totalSnowDepth"
            variables: [mean, count, RMS]
          - name: "byDomains/oman/totalSnowDepth"
            variables: [mean, count, RMS]
          - name: "griddedBins/ombg/totalSnowDepth"
            variables: [mean, count, RMS]
        variables: [validTime]

    figures:
      - use: time_series_multi_line
        params:
          title: "{{ ob_type }} Time Series - Mean O-F\n[[start_YMDH]]-[[end_YMDH]]"
          variable: "totalSnowDepth"
          y_label: "Departure"
          output: "[[runtime_dir]]/plots/[[variable]]/totalSnowDepth/[[variable]]_mean_totalSnowDepth_global_time_series_[[start_YMDH]]_[[end_YMDH]].png"
          series:
            - series_label: "O-F"
              series_color: "blue"
              series_y: "ObsMonitor::byDomains_ombg_totalSnowDepth::mean"
              series_slices: "[:,-1]"
            - series_label: "O-A"
              series_color: "red"
              series_y: "ObsMonitor::byDomains_oman_totalSnowDepth::mean"
              series_slices: "[:,-1]"
