ob_types:

  prepbufr_adpsfc:
    datasets:
      - filenames_template:
          template: "{{ runtime_dir }}/prepbufr_adpsfc_%Y%m%d%H_output_atmos.nc"
        groups:
          - name: "byDomains/ombg/stationPressure"
            variables:
              - assimilated_mean
              - assimilated_count
              - assimilated_RMS
          - name: "byDomains/oman/stationPressure"
            variables:
              - assimilated_mean
              - assimilated_count
              - assimilated_RMS
          - name: "griddedBins/ombg/stationPressure"
            variables:
              - assimilated_mean
              - assimilated_count
              - assimilated_RMS
          - name: "griddedBins"
            variables:
              - latitude
              - longitude

        variables: [validTime]

    transforms:
      - transform: reduce
        source: "ObsMonitor::griddedBins_ombg_stationPressure::assimilated_mean"
        new name: "ObsMonitor::griddedBins_ombg_stationPressure::mean_cycleAvg"
        op: "mean"
        dims: ["analysisCycle"]
        skipna: true
        squeeze_binsZ: false
        mask_fill: true

    figures:
      - use: map_gridded_single
        params:
          title: "ADPSFC stationPressure O-F — Cycle Avg (gridded)"
          output: "[[runtime_dir]]/plots/adpsfc/stationPressure/adpsfc_mean_stationPressure_global_binned_avg_[[start_YMDH]]_[[end_YMDH]].png"
          colorbar_label: "hPa"
          projection: plcarr
          domain: global
          x_var: "ObsMonitor::griddedBins::longitude"
          y_var: "ObsMonitor::griddedBins::longitude"
          data_var: "ObsMonitor::griddedBins_ombg_stationPressure::mean_cycleAvg"
          data_slices: "[0,:,:]"
          cmap: "coolwarm"
